In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('sonardataset.csv')

In [3]:
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [5]:
df.shape

(208, 61)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [7]:
df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [8]:
df['Y'].value_counts()

Y
M    111
R     97
Name: count, dtype: int64

In [9]:
x = df.drop('Y',axis=1)
y=df['Y']

In [10]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, classification_report ,confusion_matrix

In [12]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import layers

In [13]:
encoder=LabelEncoder()
y_int= encoder.fit_transform(y)

In [14]:
x_train, x_test, y_train, y_test = train_test_split(
...     x, y_int, test_size=0.2, random_state=42,stratify=y_int)

In [16]:
print(X_train_scaled.shape)

(166, 60)

In [26]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [34]:
model=Sequential([

    Dense(16,input_dim=60,activation='relu'),
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')
])

In [35]:
print("X_train_scaled shape:", X_train_scaled.shape)
print("y_train shape:", y_train.shape)
print("Unique values in y_train:", np.unique(y_train))
print("Data type of y_train:", y_train.dtype)

X_train_scaled shape: (166, 60)
y_train shape: (166, 1)
Unique values in y_train: [0 1]
Data type of y_train: int64

In [40]:
y_train = y_train.reshape(-1, 1)

In [37]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [38]:
history = model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.4924 - loss: 0.7390 - val_accuracy: 0.6471 - val_loss: 0.6077
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5909 - loss: 0.6530 - val_accuracy: 0.8529 - val_loss: 0.5625
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7197 - loss: 0.5933 - val_accuracy: 0.8529 - val_loss: 0.5434
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7879 - loss: 0.5469 - val_accuracy: 0.8529 - val_loss: 0.5252
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8030 - loss: 0.5093 - val_accuracy: 0.8529 - val_loss: 0.5010
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8182 - loss: 0.4777 - val_accuracy: 0.8529 - val_loss: 0.4748
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8182 - loss: 0.4500 - val_accuracy: 0.8235 - val_loss: 0.4464
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.4242 - val_accuracy: 0.8235 - val_loss: 0.4144
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8485 - loss: 0.3962 - val_accuracy: 0.8529 - val_loss: 0.3958
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8561 - loss: 0.3681 - val_accuracy: 0.8529 - val_loss: 0.3803
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8864 - loss: 0.3422 - val_accuracy: 0.8529 - val_loss: 0.3592
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8864 - loss: 0.3166 - val_accuracy: 0.8529 - val_loss: 0.3367
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9091 - loss: 0.2934 - val_accuracy: 0.8529 - val_loss: 0.3220
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9091 - loss: 0.2725 - val_accuracy: 0.8529 - val_loss: 0.3145
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9242 - loss: 0.2499 - val_accuracy: 0.8529 - val_loss: 0.3132
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9242 - loss: 0.2306 - val_accuracy: 0.8529 - val_loss: 0.3044
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9470 - loss: 0.2139 - val_accuracy: 0.8529 - val_loss: 0.2996
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9545 - loss: 0.1963 - val_accuracy: 0.8529 - val_loss: 0.3013
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9545 - loss: 0.1830 - val_accuracy: 0.8824 - val_loss: 0.2985
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9697 - loss: 0.1690 - val_accuracy: 0.8824 - val_loss: 0.2997
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1549 - val_accuracy: 0.8824 - val_loss: 0.2943
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1418 - val_accuracy: 0.8824 - val_loss: 0.3020
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1304 - val_accuracy: 0.8824 - val_loss: 0.3048
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1204 - val_accuracy: 0.8824 - val_loss: 0.3071
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1114 - val_accuracy: 0.8824 - val_loss: 0.3071
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1019 - val_accuracy: 0.8824 - val_loss: 0.3081
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.0947 - val_accuracy: 0.8824 - val_loss: 0.3185
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9773 - loss: 0.0867 - val_accuracy: 0.8824 - val_loss: 0.3275
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0815 - val_accuracy: 0.8824 - val_loss: 0.3207
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0737 - val_accuracy: 0.8824 - val_loss: 0.3352
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0691 - val_accuracy: 0.8824 - val_loss: 0.3401
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0646 - val_accuracy: 0.8529 - val_loss: 0.3424
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0595 - val_accuracy: 0.8529 - val_loss: 0.3540
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0550 - val_accuracy: 0.8529 - val_loss: 0.3550
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0516 - val_accuracy: 0.8529 - val_loss: 0.3559
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0484 - val_accuracy: 0.8529 - val_loss: 0.3583
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0451 - val_accuracy: 0.8529 - val_loss: 0.3679
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0411 - val_accuracy: 0.8529 - val_loss: 0.3703
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0374 - val_accuracy: 0.8529 - val_loss: 0.3716
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0338 - val_accuracy: 0.8529 - val_loss: 0.3728
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0307 - val_accuracy: 0.8529 - val_loss: 0.3781
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0280 - val_accuracy: 0.8529 - val_loss: 0.3901
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0255 - val_accuracy: 0.8529 - val_loss: 0.3966
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0236 - val_accuracy: 0.8529 - val_loss: 0.4091
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0213 - val_accuracy: 0.8529 - val_loss: 0.4138
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0196 - val_accuracy: 0.8529 - val_loss: 0.4161
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0181 - val_accuracy: 0.8529 - val_loss: 0.4253
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0168 - val_accuracy: 0.8529 - val_loss: 0.4301
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0154 - val_accuracy: 0.8529 - val_loss: 0.4353
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0142 - val_accuracy: 0.8529 - val_loss: 0.4378
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0132 - val_accuracy: 0.8235 - val_loss: 0.4434
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0122 - val_accuracy: 0.8235 - val_loss: 0.4469
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0113 - val_accuracy: 0.8235 - val_loss: 0.4531
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0106 - val_accuracy: 0.8235 - val_loss: 0.4556
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0098 - val_accuracy: 0.8235 - val_loss: 0.4655
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.8235 - val_loss: 0.4682
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.8235 - val_loss: 0.4717
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0081 - val_accuracy: 0.8235 - val_loss: 0.4741
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.8235 - val_loss: 0.4811
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0071 - val_accuracy: 0.8235 - val_loss: 0.4856
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.8235 - val_loss: 0.4882
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0063 - val_accuracy: 0.8235 - val_loss: 0.4906
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.8235 - val_loss: 0.4952
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.8235 - val_loss: 0.4984
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8235 - val_loss: 0.5026
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.8235 - val_loss: 0.5068
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.8235 - val_loss: 0.5075
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.8235 - val_loss: 0.5122
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.8235 - val_loss: 0.5175
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.8235 - val_loss: 0.5220
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.8235 - val_loss: 0.5238
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.8235 - val_loss: 0.5264
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.8235 - val_loss: 0.5297
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.8235 - val_loss: 0.5328
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0034 - val_accuracy: 0.8235 - val_loss: 0.5340
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.8235 - val_loss: 0.5382
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.8235 - val_loss: 0.5404
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.8235 - val_loss: 0.5429
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.8235 - val_loss: 0.5462
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.8235 - val_loss: 0.5490
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.8235 - val_loss: 0.5519
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.8235 - val_loss: 0.5559
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.8235 - val_loss: 0.5583
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.8235 - val_loss: 0.5605
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.8235 - val_loss: 0.5642
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8235 - val_loss: 0.5647
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.8235 - val_loss: 0.5657
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.8235 - val_loss: 0.5686
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.8235 - val_loss: 0.5715
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8235 - val_loss: 0.5745
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8235 - val_loss: 0.5773
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8235 - val_loss: 0.5794
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8235 - val_loss: 0.5808
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.8235 - val_loss: 0.5838
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8235 - val_loss: 0.5861
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8235 - val_loss: 0.5876
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8235 - val_loss: 0.5909
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8235 - val_loss: 0.5944
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8235 - val_loss: 0.5963
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8235 - val_loss: 0.5974

In [58]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [59]:

y_pred_proba = model.predict(X_test_scaled)


y_pred = (y_pred_proba >= 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

In [60]:
# Compute the numbers
acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Print them
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-Score:  {f1:.4f}")

# Or use classification_report to see all at once (includes 0 and 1 classes)
print(classification_report(y_test, y_pred, target_names=['Fail', 'Pass']))

Accuracy:  0.8333
Precision: 0.9333
Recall:    0.7000
F1-Score:  0.8000
              precision    recall  f1-score   support

        Fail       0.78      0.95      0.86        22
        Pass       0.93      0.70      0.80        20

    accuracy                           0.83        42
   macro avg       0.86      0.83      0.83        42
weighted avg       0.85      0.83      0.83        42

In [43]:
# tuned model

In [44]:
model1=Sequential([

    Dense(16,input_dim=60,activation='relu'),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [45]:
y_train = y_train.reshape(-1, 1)

In [46]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [47]:
history = model1.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step - accuracy: 0.4773 - loss: 0.6984 - val_accuracy: 0.7059 - val_loss: 0.6651
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5682 - loss: 0.6548 - val_accuracy: 0.6765 - val_loss: 0.6583
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6212 - loss: 0.6224 - val_accuracy: 0.6471 - val_loss: 0.6497
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6742 - loss: 0.5952 - val_accuracy: 0.7353 - val_loss: 0.6259
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7348 - loss: 0.5651 - val_accuracy: 0.7647 - val_loss: 0.6009
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7348 - loss: 0.5334 - val_accuracy: 0.7941 - val_loss: 0.5674
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4994 - val_accuracy: 0.7941 - val_loss: 0.5232
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8258 - loss: 0.4621 - val_accuracy: 0.8235 - val_loss: 0.4747
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4228 - val_accuracy: 0.8235 - val_loss: 0.4294
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8636 - loss: 0.3839 - val_accuracy: 0.8235 - val_loss: 0.3998
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8939 - loss: 0.3455 - val_accuracy: 0.8529 - val_loss: 0.3761
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9015 - loss: 0.3121 - val_accuracy: 0.8529 - val_loss: 0.3582
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.2787 - val_accuracy: 0.8529 - val_loss: 0.3468
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9242 - loss: 0.2489 - val_accuracy: 0.8529 - val_loss: 0.3350
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9242 - loss: 0.2228 - val_accuracy: 0.8529 - val_loss: 0.3323
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9318 - loss: 0.2010 - val_accuracy: 0.8529 - val_loss: 0.3331
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9318 - loss: 0.1825 - val_accuracy: 0.8529 - val_loss: 0.3329
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9545 - loss: 0.1653 - val_accuracy: 0.8529 - val_loss: 0.3462
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9470 - loss: 0.1502 - val_accuracy: 0.8529 - val_loss: 0.3476
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9545 - loss: 0.1367 - val_accuracy: 0.8529 - val_loss: 0.3505
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9545 - loss: 0.1273 - val_accuracy: 0.8529 - val_loss: 0.3670
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9545 - loss: 0.1167 - val_accuracy: 0.8529 - val_loss: 0.3753
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9621 - loss: 0.1096 - val_accuracy: 0.8529 - val_loss: 0.3851
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9621 - loss: 0.1002 - val_accuracy: 0.8824 - val_loss: 0.3764
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.0938 - val_accuracy: 0.8824 - val_loss: 0.3908
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9621 - loss: 0.0884 - val_accuracy: 0.8824 - val_loss: 0.4066
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0826 - val_accuracy: 0.8824 - val_loss: 0.4200
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0761 - val_accuracy: 0.8824 - val_loss: 0.4146
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0707 - val_accuracy: 0.8824 - val_loss: 0.4293
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.0650 - val_accuracy: 0.8824 - val_loss: 0.4421
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0616 - val_accuracy: 0.8824 - val_loss: 0.4626
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.0580 - val_accuracy: 0.8824 - val_loss: 0.4662
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9848 - loss: 0.0544 - val_accuracy: 0.8824 - val_loss: 0.4721
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0491 - val_accuracy: 0.8824 - val_loss: 0.4810
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0447 - val_accuracy: 0.8824 - val_loss: 0.4895
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0406 - val_accuracy: 0.8824 - val_loss: 0.5019
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9924 - loss: 0.0356 - val_accuracy: 0.8824 - val_loss: 0.5124
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0329 - val_accuracy: 0.8824 - val_loss: 0.5167
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0285 - val_accuracy: 0.8824 - val_loss: 0.5233
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0249 - val_accuracy: 0.8824 - val_loss: 0.5370
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0228 - val_accuracy: 0.8824 - val_loss: 0.5427
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0190 - val_accuracy: 0.8824 - val_loss: 0.5610
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0170 - val_accuracy: 0.8824 - val_loss: 0.5667
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0157 - val_accuracy: 0.8824 - val_loss: 0.5769
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.9118 - val_loss: 0.5868
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0132 - val_accuracy: 0.8824 - val_loss: 0.6006
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0121 - val_accuracy: 0.8824 - val_loss: 0.6052
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0112 - val_accuracy: 0.8824 - val_loss: 0.6154
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0105 - val_accuracy: 0.8824 - val_loss: 0.6246
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0096 - val_accuracy: 0.8824 - val_loss: 0.6315
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0091 - val_accuracy: 0.9118 - val_loss: 0.6334
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0084 - val_accuracy: 0.8824 - val_loss: 0.6468
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0079 - val_accuracy: 0.8824 - val_loss: 0.6512
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.8824 - val_loss: 0.6589
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.8824 - val_loss: 0.6665
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0065 - val_accuracy: 0.8824 - val_loss: 0.6719
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0061 - val_accuracy: 0.8824 - val_loss: 0.6777
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 0.8824 - val_loss: 0.6828
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.8824 - val_loss: 0.6879
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.8824 - val_loss: 0.6949
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0048 - val_accuracy: 0.8824 - val_loss: 0.7014
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0046 - val_accuracy: 0.8824 - val_loss: 0.7052
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0043 - val_accuracy: 0.8824 - val_loss: 0.7105
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.8824 - val_loss: 0.7139
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.8824 - val_loss: 0.7202
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.8824 - val_loss: 0.7250
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.8824 - val_loss: 0.7307
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.8824 - val_loss: 0.7332
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.8824 - val_loss: 0.7385
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.8824 - val_loss: 0.7441
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.8824 - val_loss: 0.7451
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.8824 - val_loss: 0.7507
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.8824 - val_loss: 0.7555
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.8824 - val_loss: 0.7574
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.8824 - val_loss: 0.7608
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.8824 - val_loss: 0.7640
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8824 - val_loss: 0.7676
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.8824 - val_loss: 0.7717
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.8824 - val_loss: 0.7761
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8824 - val_loss: 0.7801
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8824 - val_loss: 0.7816
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8824 - val_loss: 0.7882
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.8824 - val_loss: 0.7899
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.8824 - val_loss: 0.7925
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.8824 - val_loss: 0.7960
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8824 - val_loss: 0.7985
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.8824 - val_loss: 0.8027
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8824 - val_loss: 0.8046
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.8824 - val_loss: 0.8095
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.8824 - val_loss: 0.8111
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.8824 - val_loss: 0.8149
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.8181
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.8202
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.8824 - val_loss: 0.8213
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.8237
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.8290
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8824 - val_loss: 0.8298
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.8824 - val_loss: 0.8316
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.8973e-04 - val_accuracy: 0.8824 - val_loss: 0.8345
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.5829e-04 - val_accuracy: 0.8824 - val_loss: 0.8374

In [63]:

y_pred_proba1 = model1.predict(X_test_scaled)


y_pred1 = (y_pred_proba1 >= 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

In [64]:
# Compute the numbers
acc = accuracy_score(y_test, y_pred1)
prec = precision_score(y_test, y_pred1)
rec = recall_score(y_test, y_pred1)
f1 = f1_score(y_test, y_pred1)

# Print them
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-Score:  {f1:.4f}")

# Or use classification_report to see all at once (includes 0 and 1 classes)
print(classification_report(y_test, y_pred, target_names=['Fail', 'Pass']))

Accuracy:  0.8333
Precision: 0.9333
Recall:    0.7000
F1-Score:  0.8000
              precision    recall  f1-score   support

        Fail       0.78      0.95      0.86        22
        Pass       0.93      0.70      0.80        20

    accuracy                           0.83        42
   macro avg       0.86      0.83      0.83        42
weighted avg       0.85      0.83      0.83        42

In [ ]:
## in the deafult model i have 1 hidden layer and tuned model i have 2 hidden layers with differnt number of neurons but due to small dataset both the model gives the same accurcay  ia have implemeted all the required steps.