In [25]:
import pandas as pd

## 1

In [4]:
df=pd.read_csv('Patient_Data.csv')
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [6]:
df.describe

<bound method NDFrame.describe of    PatientID     Name   Department     Doctor  BillAmount  ReceptionistID  \
0        101    Alice   Cardiology  Dr. Smith      5000.0               1
1        102      Bob    Neurology   Dr. John         NaN               2
2        103  Charlie  Orthopedics    Dr. Lee      7500.0               1
3        104    David   Cardiology  Dr. Smith      6200.0               3
4        105      Eva  Dermatology   Dr. Rose         NaN               2
5        101    Alice   Cardiology  Dr. Smith      5000.0               1

        CheckInTime
0  2023-01-10 09:00
1  2023-01-11 10:30
2  2023-01-12 11:00
3  2023-01-13 12:00
4  2023-01-14 08:45
5  2023-01-10 09:00  >

## 2

In [15]:
sd = df[['PatientID','Department','Doctor','BillAmount']]

In [14]:
print(sd)

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

## 3

In [28]:
df.drop(['ReceptionistID','CheckInTime'], axis=1)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

## 4

In [31]:
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

## 5

In [33]:
df.drop_duplicates('PatientID')

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

## 6

In [34]:
sum=df['BillAmount'].mean()

In [35]:
df['BillAmount'].fillna(sum, inplace=True)

In [36]:
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,5925.0,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,5925.0,2,2023-01-14 08:45

In [37]:
df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology     5925.0
Neurology       5925.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [39]:
dg=pd.read_csv('Billing_Data.csv')
dg.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

## 7

In [40]:
pd.merge(df,dg, on='PatientID')

,PatientID,InsuranceCovered_x,FinalAmount_x,InsuranceCovered_y,FinalAmount_y
0,101,2000,3000,2000,3000
1,102,1500,3500,1500,3500
2,103,2500,5000,2500,5000
3,104,3000,3200,3000,3200
4,105,1000,4000,1000,4000

## 8

In [42]:
df_combined = pd.concat([df, dg], axis=0)
df_combined

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

## 9

In [43]:
df_combined1 = pd.concat([df, dg], axis=1)
df_combined1

,PatientID,InsuranceCovered,FinalAmount,PatientID,InsuranceCovered,FinalAmount
0,101,2000,3000,101,2000,3000
1,102,1500,3500,102,1500,3500
2,103,2500,5000,103,2500,5000
3,104,3000,3200,104,3000,3200
4,105,1000,4000,105,1000,4000